# Generated by Django 3.1.4 on 2021-01-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecategory',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='game_categories', related_query_name='game_category', to='raterapi.Categories'),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raterapi.categories'),
            preserve_default=False,
        ),
    ]
